/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface SFunboxCards {
        /**
          * Данные для карточки
         */
        "cardContent": any;
    }
    interface SFunboxCardsWrapper {
        /**
          * Background image
         */
        "bgImage": string;
        /**
          * Данные для карточки
         */
        "cardContent": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSFunboxCardsElement extends Components.SFunboxCards, HTMLStencilElement {
    }
    var HTMLSFunboxCardsElement: {
        prototype: HTMLSFunboxCardsElement;
        new (): HTMLSFunboxCardsElement;
    };
    interface HTMLSFunboxCardsWrapperElement extends Components.SFunboxCardsWrapper, HTMLStencilElement {
    }
    var HTMLSFunboxCardsWrapperElement: {
        prototype: HTMLSFunboxCardsWrapperElement;
        new (): HTMLSFunboxCardsWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "s-funbox-cards": HTMLSFunboxCardsElement;
        "s-funbox-cards-wrapper": HTMLSFunboxCardsWrapperElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface SFunboxCards {
        /**
          * Данные для карточки
         */
        "cardContent"?: any;
        /**
          * Клик по карточке
         */
        "onClickOnCard"?: (event: CustomEvent<any>) => void;
    }
    interface SFunboxCardsWrapper {
        /**
          * Background image
         */
        "bgImage"?: string;
        /**
          * Данные для карточки
         */
        "cardContent"?: any;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "s-funbox-cards": SFunboxCards;
        "s-funbox-cards-wrapper": SFunboxCardsWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "s-funbox-cards": LocalJSX.SFunboxCards & JSXBase.HTMLAttributes<HTMLSFunboxCardsElement>;
            "s-funbox-cards-wrapper": LocalJSX.SFunboxCardsWrapper & JSXBase.HTMLAttributes<HTMLSFunboxCardsWrapperElement>;
        }
    }
}
